// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Speedrun.Models;

#nullable disable

namespace Speedrun.Api.Migrations
{
    [DbContext(typeof(SRDbContext))]
    partial class SRDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Speedrun.Models.SRSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MsDuration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SRStrainId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SRStrainId");

                    b.ToTable("SRSegment");
                });

            modelBuilder.Entity("Speedrun.Models.SRStrain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SRSystemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SRSystemId");

                    b.ToTable("SRStrain");
                });

            modelBuilder.Entity("Speedrun.Models.SRSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SRSystem");
                });

            modelBuilder.Entity("Speedrun.Models.SRSegment", b =>
                {
                    b.HasOne("Speedrun.Models.SRStrain", "SRStrain")
                        .WithMany("SRSegments")
                        .HasForeignKey("SRStrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SRStrain");
                });

            modelBuilder.Entity("Speedrun.Models.SRStrain", b =>
                {
                    b.HasOne("Speedrun.Models.SRSystem", "SRSystem")
                        .WithMany("SRStrains")
                        .HasForeignKey("SRSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SRSystem");
                });

            modelBuilder.Entity("Speedrun.Models.SRStrain", b =>
                {
                    b.Navigation("SRSegments");
                });

            modelBuilder.Entity("Speedrun.Models.SRSystem", b =>
                {
                    b.Navigation("SRStrains");
                });
#pragma warning restore 612, 618
        }
    }
}
